### PR TITLE
Fix Panel Chat Pack

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
As a follow up to the release of https://github.com/run-llama/llama-hub/pull/703, I tested the released version out and identified some issues.

- The cute llama asset is not shown on the hub or in the app
- The screenshot has a line of my start bar at the bottom
- When the pack has been installed, users will not be able to start it with `panel serve ..` or `python ..` as described because the `.run` method is never run.

This PR fixes it.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Just for info. Maybe the next PR should be a tool to create plots (matplotlib, bokeh or plotly) via hvPlot and natural language 😄 

https://github.com/run-llama/llama-hub/assets/42288570/fdbdfe19-40a5-417a-b34c-6256dece76a0

**Review by jerryjliu — APPROVED** [review]
out of curiosity did you test/verify these changes?

**Comment by jerryjliu** [comment]
> Just for info. Maybe the next PR should be a tool to create plots (matplotlib, bokeh or plotly) via hvPlot and natural language 😄
> 
>  chat-with-hvplot.mp4

plots sound good :) also we have multi-modal support with LLaVa, GPT-4V, and that could be a fun demo as well? https://docs.llamaindex.ai/en/latest/use_cases/multimodal.html

**Comment by MarcSkovMadsen** [comment]
Oh. That could be a dream. When we created the Panel chat components we really wanted to support multi-modal use cases.

**Comment by MarcSkovMadsen** [comment]
> out of curiosity did you test/verify these changes?

Yes. Manually.

**Comment by jerryjliu** [comment]
> > out of curiosity did you test/verify these changes?
> 
> Yes. Manually.

sounds good

**Pull request merged**
