### PR TITLE
Update AzStorageBlobReader

### PR DESCRIPTION
**Pull request by JAlexMcGraw**
# Description

Added functionality to allow user to connect to blob storage with a connection string, instead of credentials and account URL. The credentials and URL functionality still exists. The motivation behind this was on a current work project, using the credentials and account URL did not function. Permissions weren't set right, but using the connection string, I could connect and I had one less parameter to specify.

Changed the temporary file names from random names to the names that are assigned in the container originally. The rationale is that sometimes the original names are needed later on, such as my case that the names were used to create metadata, which could not be done with random names. 

Updated README to reflect this new functionality, and added a tip on how to update file_extractor file to specify a specific different document reader, if needed. Updated library to reflect myself as a contributor/author to this module.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix / Smaller change
- [ ] This change requires a documentation update

# How Has This Been Tested?

Created an AzStorageBlobReader instance using only the container name and connection string for the storage account, and was able to load data using the .load_data() method.

To test yourself, instead of specifying a container name, credentials, and account URL, can specify just the container name and connection string. Then, run the load_data() method on the class instantiation.

- [ ] Added new notebook (that tests end-to-end) (Tested this locally and it worked, but did not upload. Would you like me to upload?)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have added a library.json file if a new loader/tool was added
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes (did not test)

### CODE REVIEW

**Review by anoopshrma — APPROVED** [review]

**Comment by anoopshrma** [comment]
Awesome! Thanks for the contribution! 
All looks good for merge except linting, Could you take a look at that!!

**Comment by JAlexMcGraw** [comment]
Fixed linting. Should be good to go!

**Comment by nerdai** [comment]
Thanks @JAlexMcGraw for the contribution. FYI, I had to remove your name in `library.json` as entering a list of authors at current moment breaks the UI.

In lieu of not being listed as an author, I added an UPDATES section in the README indicating what updates you have made to this pack.

(cc @anoopshrma for future reference :) )

**Comment by anoopshrma** [comment]
Ah I see, Thanks for the heads up @nerdai  🙌 
will keep this in mind

**Pull request merged**
