### PR TITLE
Update pandas excel reader

### PR DESCRIPTION
**Pull request by Navanit-git**
In this earlier the excel merge all the documents in as a whole but in this update, I gave user a choice to get the different documents for different sheets.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] New Loader/Tool
- [x] Bug fix / Smaller change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have added a library.json file if a new loader/tool was added
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by Navanit-git** [comment]
@jerryjliu kindly review it.

**Review by nerdai — APPROVED** [review]
lgtm @Navanit-git - thanks for the update!

I think perhaps its worth updating the README as well to reflect these updates. It'd be good to merge afterwards :)

**Comment by anoopshrma** [comment]
Also if possible, Update the readme file for Llamahub link

Currently it is like this: See [here](https://github.com/emptycrown/llama-hub/tree/main) for examples.

Update it to: See [here](https://github.com/run-llama/llama-hub/tree/main/llama_hub) for examples.

**Comment by Navanit-git** [comment]
@anoopshrma I didn't get the "Update the readme file for Llamahub link"
As I have update the readme with the necessary changes as per requested by @nerdai

**Comment by Navanit-git** [comment]
@nerdai Thank you for your feedback. Kindly merge the PR

**Comment by nerdai** [comment]
> @nerdai Thank you for your feedback. Kindly merge the PR 

Hey can't merge yet as lint checks haven't passed. Please run "make format" followed by "make lint" and push changes up.

**Comment by Navanit-git** [comment]
> > @nerdai Thank you for your feedback. Kindly merge the PR
> 
> Hey can't merge yet as lint checks haven't passed. Please run "make format" followed by "make lint" and push changes up.

sure will update the readme by fixing the lints

**Pull request closed without merging**
