### PR TITLE
feat: add StripeDocsReader loader

### PR DESCRIPTION
**Pull request by amorriscode**
# Description

Adds `StripeDocsReader` to use RAG on the Stripe documentation.

## Type of Change

Please delete options that are not relevant.

- [x] New Loader

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have added a library.json file if a new loader/tool was added
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]
this looks great!! thanks for the contribution

**Comment by amorriscode** [comment]
@jerryjliu looks like I had to use `List` from `typing`. I was developing on Python 3.9 and using `list` locally but I think the CI tests failed because of that.

**Comment by jerryjliu** [comment]
> @jerryjliu looks like I had to use `List` from `typing`. I was developing on Python 3.9 and using `list` locally but I think the CI tests failed because of that.

ohh i see. thanks for fixing! rerunning CI now, if needed i can jump in to merge later today

**Comment by amorriscode** [comment]
> > @jerryjliu looks like I had to use `List` from `typing`. I was developing on Python 3.9 and using `list` locally but I think the CI tests failed because of that.
> 
> ohh i see. thanks for fixing! rerunning CI now, if needed i can jump in to merge later today

Embarrassingly I missed the use of `list` in the test. Should be good now. 🤞🏻

**Comment by jerryjliu** [comment]
> > > @jerryjliu looks like I had to use `List` from `typing`. I was developing on Python 3.9 and using `list` locally but I think the CI tests failed because of that.
> > 
> > 
> > ohh i see. thanks for fixing! rerunning CI now, if needed i can jump in to merge later today
> 
> Embarrassingly I missed the use of `list` in the test. Should be good now. 🤞🏻

awesome thanks!!

**Pull request merged**
