### PR TITLE
Create llama_packs_neo4j.ipynb

### PR DESCRIPTION
**Pull request by wenqiglantz**
# Description

Adding test notebook for Neo4j query engine pack.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x ] Bug fix / Smaller change

# How Has This Been Tested?

This notebook itself is a test for neo4j_query_engine pack.

- [ ] Added new unit/integration tests
- [x ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have added a library.json file if a new loader/tool was added
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — APPROVED** [review]
This looks great @wenqiglantz! Thank you 🙏

**Comment by nerdai** [comment]
merging this now too.

**Review by jerryjliu — APPROVED** [review]
this looks good! some small notes but approving to unblock
- would be nice to add a colab badge
```
<a href=\"https://colab.research.google.com/github/run-llama/llama-hub/blob/main/llama_hub/llama_packs/neo4j_query_engine/llama_packs_neo4j.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>
```

- nit: `!pip install llama-index llama-hub neo4j`

**Comment by jerryjliu** [comment]
oh oops

**Pull request merged**
