### PR TITLE
Add retries arg to github reader

### PR DESCRIPTION
**Pull request by rwood-97**
# Description

This implements #953 

## Type of Change

- [x] Bug fix / Smaller change

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by rwood-97** [comment]
Going to do this on llama-index repo

**Comment by rwood-97** [comment]
I'm back here

**Comment by jerryjliu** [comment]
@rwood-97 was there an issue with porting the change over to the main llama-index repo? llama_hub as a repo is now deprecated

**Comment by rwood-97** [comment]
Hey sorry, I ran out of time getting this done on Friday but have blocked off some time on Wednesday next week to do this plus migrate our repo to the new llama-index.

Part of the problem was that the github repo reader had lost some functionality in the llama_index repo vs llama_hub so I was going to tackle that but it looks like its been done already (thanks!): 
https://github.com/run-llama/llama_index/pull/10953
https://github.com/run-llama/llama_index/pull/10949

Hopefully this PR will now be simpler to transfer across, I'll close it when I've made the PR there just to keep track if thats okay.

**Pull request closed without merging**
